CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    subscription_status VARCHAR(255) NOT NULL DEFAULT 'FREE',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS interview_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    role VARCHAR(255),
    created_at TIMESTAMP,
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS question_bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255),
    topic VARCHAR(255),
    difficulty VARCHAR(255),
    question_text VARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS session_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    question_id BIGINT,
    order_index INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS session_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_session_answer_session_question UNIQUE (session_id, question_id)
);

CREATE TABLE IF NOT EXISTS question_evaluation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    strengths TEXT NOT NULL,
    weaknesses TEXT NOT NULL,
    feedback TEXT NOT NULL,
    model_answer TEXT,
    evaluation_error BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_question_evaluation_session_question UNIQUE (session_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_interview_session_user_id ON interview_session (user_id);
CREATE INDEX IF NOT EXISTS idx_question_bank_role ON question_bank (role);
CREATE INDEX IF NOT EXISTS idx_session_question_session_id ON session_question (session_id);
CREATE INDEX IF NOT EXISTS idx_session_answer_session_id ON session_answer (session_id);
CREATE INDEX IF NOT EXISTS idx_question_evaluation_session_id ON question_evaluation (session_id);
