CREATE TABLE IF NOT EXISTS email_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email_type VARCHAR(100) NOT NULL,
    external_event_id VARCHAR(255),
    provider_message_id VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    error_message VARCHAR(1000),
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email_deliveries_user_id ON email_deliveries (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_email_deliveries_type_external_event
    ON email_deliveries (email_type, external_event_id);
