spring.application.name=interviewos
spring.profiles.default=dev

jwt.secret=${JWT_SECRET}

app.auth.cookie.name=access_token
app.auth.cookie.same-site=Lax
app.auth.cookie.max-age-seconds=3600
app.rate-limit.redis.enabled=false
spring.data.redis.repositories.enabled=false

server.tomcat.max-http-form-post-size=2MB
server.tomcat.max-swallow-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.servlet.multipart.max-file-size=2MB
server.max-http-request-header-size=16KB
