package com.asad.interviewos.interviews.domain;
public enum QuestionTopic {

    ANALYTICS,
    API_DESIGN,
    ARCHITECTURE,
    CACHING,
    DATABASES,
    CONCURRENCY,
    CUSTOMERS,
    EXECUTION,
    EXPERIMENTATION,
    FEATURE_ENGINEERING,
    MESSAGING,
    ML_SYSTEMS,
    SYSTEM_DESIGN,
    SECURITY,

    STATISTICS,
    MACHINE_LEARNING,
    DATA_CLEANING,
    MODEL_EVALUATION,
    MODELING,
    PERFORMANCE,

    PRODUCT_SENSE,
    PRODUCT_STRATEGY,
    METRICS,
    ROADMAP,
    STAKEHOLDERS
}
